# Generated by Django 3.0.3 on 2020-02-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='short_urls',
            options={'verbose_name': 'Short URL', 'verbose_name_plural': 'Short URLs'},
        ),
        migrations.AlterField(
            model_name='short_urls',
            name='long_url',
            field=models.URLField(blank=True, unique=True, verbose_name='URL'),
        ),
    ]
