# Generated by Django 3.0.3 on 2020-02-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0002_auto_20200210_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_urls',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='short_urls',
            name='long_url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='short_urls',
            name='short_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
