# Generated by Django 3.0.3 on 2020-02-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0003_auto_20200210_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_urls',
            name='short_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
